config/routes.rb
Activerecord::Application.routes.draw do
  resources :products 
  resources :items
  resources :images
  resources :carts
  
match "menu" => "products#menu"

  get "home/index"

root :to => 'home#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :totalprice
  has_many :items
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :location
  has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  has_and_belongs_to_many :images
  attr_accessible :num_images
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :max_images, :name, :price
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
	def index
    @carts= Cart.all
    end
	


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
def index
    @images = Image.all
    end

# GET /images/1
  # GET /images/1.json
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
   end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
    @items = Item.all
    end

# GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

# POST /items
  # POST /items.json
  def create
    @item= @Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

# GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
   end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

 def menu
    @products = Product.all

    respond_to do |format|
      format.html # menu.html.erb
      format.json { render json: @products }
    end
  end



  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/index.html.erb
<h1>Cart Contents</h1>

<table table class="table table-bordered">
  <tr>
    <th>Cart Id</th>
    <th>List of items</th>
    <th>Cart Total</th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.id %></td>
    <td>need to string together list of items</td>
    <td><%= cart.totalprice %></td>
  </tr>
<% end %>
</table>



<br />
<%= link_to 'Back', home_index_path %>

app/views/home/index.html.erb
<h1>Home Page</h1>

<br />
<%= link_to "Create new products", products_path %>
<br />
<%= link_to "Product Menu", menu_path %>
<br />
<%= link_to "List of Items", items_path %>
<br />
<%= link_to "List of Images", images_path %>

app/views/images/index.html.erb
<h1>List of Images</h1>

<table table class="table table-bordered">
  <tr>
    <th>Image Id</th>
    <th>Image Location</th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.id %></td>
    <td><%= image.location %></td>
  </tr>
<% end %>
</table>



<br />
<%= link_to 'Back', home_index_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  

  <div class="field">
    <%= f.label :num_images %><br />
    <%= f.number_field :num_images %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/items/index.html.erb
<h1>List of Items</h1>

<table table class="table table-bordered">
  <tr>
    <th>Item Id</th>
    <th>Product Id</th>
    <th>Product Name</th>
    <th>Unit Price</th>
    <th>Num of images</th>
    <th>List of Image Ids</th>
    <th>Cart Id</th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.id %></td>
    <td><%= item.product_id %></td>
    <td>need to find product name via product id</td>
    <td>need to find product price via product id</td>    
    <td><%= item.num_images %></td>
    <td>need to string together list of image ids</td>
    <td><%= item.cart_id %></td>
     <td><%= link_to 'Add to Cart', carts_path %></td>
  </tr>
<% end %>
</table>




<br />
<%= link_to 'New Item', new_item_path %>
<br />
<%= link_to 'Back', home_index_path %>

app/views/items/new.html.erb
<h1>Create New Item for this product</h1>

<p>haven't built anything here yet</p>

<h2>Create a new Product Item</h2>
<%= render 'form' %>





<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product Type Id:</b>
  <%= @item.product_id %>
</p>

<p>
  <b>Number of images:</b>
  <%= @item.num_images %>
</p>




<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <title>Active Record</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
<body style="background: #EEEEEE;">

	<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :max_images %><br />
    <%= f.number_field :max_images %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Create New Products</h1>

<table table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Max images</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.max_images %></td>
    <td><%= product.price %></td>

    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Product', new_product_path %>
<br />
<%= link_to 'Back', home_index_path %>

app/views/products/menu.html.erb
<h1>Product Menu</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Max images</th>
    <th>Price</th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.max_images %></td>
    <td><%= product.price %></td>
    <td><%= link_to 'Select', new_item_path(product) %></td>
  </tr>
<% end %>
</table>

<br />



<p><%= link_to 'Back', home_index_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Max images:</b>
  <%= @product.max_images %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>